# generate rust ci

name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dprint
        run: curl -fsSL https://dprint.dev/install.sh | sh

      - name: add dprint to PATH
        run: echo "$HOME/.dprint/bin" >> "$GITHUB_PATH"

      - name: run dprint
        run: dprint check

  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: format
        run: cargo fmt --check

      - name: lint
        run: cargo clippy -- --deny warnings

      - name: build
        run: cargo test
